In [1]:
print('Hello World')

Hello World


In [2]:
import numpy as np
import sys

In [3]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = a*b
c

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [4]:
a.ndim

1

In [5]:
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
a.nbytes

12

In [11]:
#MATHEMATICS

In [12]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a + 2

array([3, 4, 5, 6])

In [14]:
a * 2

array([2, 4, 6, 8])

In [15]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [19]:
#Matrix multiplication
a = np.ones((2,3), dtype = 'int32')
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [20]:
# determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [21]:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

#### Statistics

In [22]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.min(stats)

1

In [24]:
np.max(stats, axis =1)

array([3, 6])

In [25]:
np.sum(stats, axis=0)

array([5, 7, 9])

#### Reorganizing arrays

In [26]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])